version: '3.7'
services:
  db:
    image: postgres:13
    container_name: ma-backend-db-container
    env_file:
      - .env.prod
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ma-backend-app-container
    env_file:
      - .env.prod
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
volumes:
  postgres_data:
